In [10]:
from kgap_tools import execute_to_df, generate_sparql

# Participants

#### General information about KH community day participants

In [47]:
participants = execute_to_df('participants.sparql')
participants

,person,first_name,last_name,affiliation_name
0,https://orcid.org/0000-0002-3170-3345,Emily,Veltjen,Ghent University
1,https://orcid.org/0000-0001-6302-2897,Evelien,Dhollander,Ghent University
2,https://orcid.org/0000-0002-5911-1536,Katrina,Exter,Flanders Marine Institute
3,https://orcid.org/0000-0002-5911-1536,Katrina,Exter,KU Leuven
4,https://orcid.org/0000-0002-5911-1536,Katrina,Exter,European Space Astronomy Centre
5,https://orcid.org/0000-0003-0663-5907,Laurian,Van Maldeghem,Vlaams Instituut voor de Zee
6,https://orcid.org/0000-0001-8456-3609,Charlotte A. L.,Dhondt,Flanders Marine Institute
7,https://orcid.org/0000-0001-5185-8232,Evelien,de Ferrerre,Vlerick Business School
8,https://orcid.org/0000-0002-9648-6484,Marc,Portier,Vlaams Instituut voor de Zee
9,https://orcid.org/0000-0002-4242-8553,Joanna,Goley,Flanders Marine Institute
10,https://orcid.org/0000-0001-5874-553X,Siham,Benramdane,Universiteit Antwerpen
11,https://orcid.org/0000-0003-4847-6289,Özgün,Ünver,Vrije Universiteit Brussel
12,https://orcid.org/0000-0003-4847-6289,Özgün,Ünver,KU Leuven
13,https://orcid.org/0000-0001-7415-9178,Elien,Dewitte,Instituut voor Landbouw- Visserij- en Voedings...
14,https://orcid.org/0000-0001-7415-9178,Elien,Dewitte,"Research Institute for Agriculture, Fisheries ..."
15,https://orcid.org/0000-0001-7415-9178,Elien,Dewitte,Vlaams Instituut voor de Zee
16,https://orcid.org/0000-0001-9506-766X,Paula,Oset García,Ghent University
17,https://orcid.org/0000-0001-9506-766X,Paula,Oset García,Flanders Marine Institute
18,https://orcid.org/0000-0001-9506-766X,Paula,Oset García,Gwynedd Council
19,https://orcid.org/0000-0002-0585-4203,Lyne,Van de Vyvere,University of Liège
20,https://orcid.org/0000-0001-6387-5988,Cedric,Decruw,Vlaams Instituut voor de Zee
21,https://orcid.org/0009-0008-2092-491X,Dunya,Nasser,University of Antwerp
22,https://orcid.org/0000-0002-7509-510X,Marie,Robberecht,Instituut voor Landbouw- Visserij- en Voedings...
23,https://orcid.org/0000-0002-7509-510X,Marie,Robberecht,Vlaams Instituut voor de Zee
24,https://orcid.org/0000-0002-3292-4609,Jone,Paesmans,Vrije Universiteit Brussel

#### Publications of the KH participants

In [52]:
participant_publications = execute_to_df('participants-publications.sparql')
participant_publications['name'] =  participant_publications['first_name'] + ' ' + participant_publications['last_name']

,person,first_name,last_name,pub
0,https://orcid.org/0000-0002-3170-3345,Emily,Veltjen,https://doi.org/10.3390/plants10040673
1,https://orcid.org/0000-0002-3170-3345,Emily,Veltjen,https://doi.org/10.5281/zenodo.6511351
2,https://orcid.org/0000-0002-3170-3345,Emily,Veltjen,https://doi.org/10.1016/j.ympev.2021.107359
3,https://orcid.org/0000-0002-3170-3345,Emily,Veltjen,https://doi.org/10.3897/phytokeys.213.82627
4,https://orcid.org/0000-0002-3170-3345,Emily,Veltjen,https://doi.org/10.11646/phytotaxa.201.3.6
...,...,...,...,...
228,https://orcid.org/0000-0002-3292-4609,Jone,Paesmans,https://doi.org/10.1038/nsmb.3297
229,https://orcid.org/0000-0002-3292-4609,Jone,Paesmans,https://doi.org/10.7554/elife.64922
230,https://orcid.org/0000-0002-3292-4609,Jone,Paesmans,https://rdflib.github.io/.well-known/genid/rdf...
231,https://orcid.org/0000-0002-9313-4985,Ziad,Choueiki,https://doi.org/10.3390/foods10092147
232,https://orcid.org/0000-0002-9313-4985,Ziad,Choueiki,https://doi.org/10.1016/j.ecoser.2022.101444

In [53]:
partcipant_pub_count = participant_publications.groupby('person').nunique().drop(columns=['first_name', 'last_name'], inplace=True)

                                       first_name  last_name  pub
person
https://orcid.org/0000-0001-5185-8232           1          1    2
https://orcid.org/0000-0001-5874-553X           1          1    4
https://orcid.org/0000-0001-6302-2897           1          1    3
https://orcid.org/0000-0001-6387-5988           1          1    2
https://orcid.org/0000-0001-7126-6103           1          1    8
https://orcid.org/0000-0001-7415-9178           1          1    1
https://orcid.org/0000-0001-9506-766X           1          1   22
https://orcid.org/0000-0002-0585-4203           1          1    7
https://orcid.org/0000-0002-3170-3345           1          1   13
https://orcid.org/0000-0002-3292-4609           1          1    6
https://orcid.org/0000-0002-4242-8553           1          1    2
https://orcid.org/0000-0002-5911-1536           1          1  153
https://orcid.org/0000-0002-9313-4985           1          1    2
https://orcid.org/0000-0003-0663-5907           1          1    2
https://orcid.org/0000-0003-4847-6289           1          1    6

In [ ]:
partcipant_pub_count = participant_publications.groupby('first_name').nunique().drop(columns=['first_name', 'last_name'], inplace=True)
df.plot(kind='bar', x=partcipant_pub_count, y='Population', color='skyblue')

In [43]:
test = execute_to_df('participants-test.sparql')
test

                                                   p
0    http://www.w3.org/1999/02/22-rdf-syntax-ns#type
1                       http://schema.org/familyName
2                       http://schema.org/identifier
3                          http://schema.org/address
4                              http://schema.org/url
5                    http://schema.org/alternateName
6                      http://schema.org/affiliation
7                        http://schema.org/givenName
8                         http://schema.org/alumniOf
9                 http://schema.org/mainEntityOfPage
10            http://xmlns.com/foaf/0.1/publications
11        http://www.w3.org/2000/01/rdf-schema#label
12             http://xmlns.com/foaf/0.1/accountName
13               http://xmlns.com/foaf/0.1/givenName
14                 http://xmlns.com/foaf/0.1/account
15  http://xmlns.com/foaf/0.1/accountServiceHomepage
16              http://xmlns.com/foaf/0.1/familyName
17                    http://xmlns.com/foaf/0.1/page
18              http://xmlns.com/foaf/0.1/based_near
19                    http://xmlns.com/foaf/0.1/mbox

### Organizations

In [21]:
organizations = execute_to_df('organizations.sparql')
organizations